export const INIT_LINK = 'INIT_LINK';
export const CLIENTS_ALL = 'CONTACTS_ALL';
export const CLIENTS_ADD = 'CONTACTS_ADD';
export const CLIENTS_SHOW_NEW = 'CONTACTS_SHOW_NEW';
export const CLIENTS_EDIT = 'CONTACTS_EDIT';
export const CLIENTS_DELETE = 'CONTACTS_DELETE';

//sagas
export const SAGA_RECEIPTS_FETCH_LIST = "SAGA_RECEIPTS_FETCH_LIST";
export const SAGA_RECEIPTS_FETCH_LIST_SUCCESS = "SAGA_RECEIPTS_FETCH_LIST_SUCCESS";
export const SAGA_ADD_RECEIPT = "SAGA_ADD_RECEIPT";
export const SAGA_ADD_RECEIPT_SUCCESS = "SAGA_ADD_RECEIPT_SUCCESS";
export const SAGA_UPDATE_RECEIPT = "SAGA_UPDATE_RECEIPT";
export const SAGA_UPDATE_RECEIPT_SUCCESS = "SAGA_UPDATE_RECEIPT_SUCCESS";
export const SAGA_GET_RECEIPT = "SAGA_GET_RECEIPT";
export const SAGA_GET_RECEIPT_SUCCESS = "SAGA_GET_RECEIPT_SUCCESS";

export const RECEIPTS_SHOW_NEW = 'RECEIPTS_SHOW_NEW';


//notification
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';