export const INIT_LINK = 'INIT_LINK';
export const CLIENTS_ALL = 'CONTACTS_ALL';
export const CLIENTS_ADD = 'CONTACTS_ADD';
export const CLIENTS_SHOW_NEW = 'CONTACTS_SHOW_NEW';
export const CLIENTS_EDIT = 'CONTACTS_EDIT';
export const CLIENTS_DELETE = 'CONTACTS_DELETE';

//sagas
export const SAGA_CLIENTS_FETCH_LIST = "SAGA_CLIENTS_FETCH_LIST";
export const SAGA_CLIENTS_FETCH_LIST_SUCCESS = "SAGA_CLIENTS_FETCH_LIST_SUCCESS";
export const SAGA_ADD_CLIENT = "SAGA_ADD_CLIENT";
export const SAGA_ADD_CLIENT_SUCCESS = "SAGA_ADD_CLIENT_SUCCESS";
export const SAGA_UPDATE_CLIENT = "SAGA_UPDATE_CLIENT";
export const SAGA_UPDATE_CLIENT_SUCCESS = "SAGA_UPDATE_CLIENT_SUCCESS";
export const SAGA_GET_CLIENT = "SAGA_GET_CLIENT";
export const SAGA_GET_CLIENT_SUCCESS = "SAGA_GET_CLIENT_SUCCESS";

// export const CLIENTS_SHOW_NEW = 'CLIENTS_SHOW_NEW';


//notification
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';