export const INIT_LINK = 'INIT_LINK';
export const CLIENTS_ALL = 'CONTACTS_ALL';
export const CLIENTS_ADD = 'CONTACTS_ADD';
export const CLIENTS_SHOW_NEW = 'CONTACTS_SHOW_NEW';
export const CLIENTS_EDIT = 'CONTACTS_EDIT';
export const CLIENTS_DELETE = 'CONTACTS_DELETE';

//sagas
export const SAGA_CLIENTS_FETCH_LIST = 'SAGA_CLIENTS_FETCH_LIST';
export const SAGA_CLIENTS_FETCH_LIST_SUCCESS = 'SAGA_CLIENTS_FETCH_LIST_SUCCESS';
export const SAGA_ADD_CLIENT = 'SAGA_ADD_CLIENT';
export const SAGA_ADD_CLIENT_SUCCESS = 'SAGA_ADD_CLIENT_SUCCESS';
export const SAGA_UPDATE_CLIENT = 'SAGA_UPDATE_CLIENT';
export const SAGA_UPDATE_CLIENT_SUCCESS = 'SAGA_UPDATE_CLIENT_SUCCESS';
export const SAGA_GET_CLIENT = 'SAGA_GET_CLIENT';
export const SAGA_GET_CLIENT_SUCCESS = 'SAGA_GET_CLIENT_SUCCESS';

export const SAGA_SIGNUP = 'SAGA_SIGNUP';
export const SAGA_SIGNUP_SUCCESS = 'SAGA_SIGNUP_SUCCESS';
export const SAGA_LOGIN = 'SAGA_LOGIN';
export const SAGA_LOGIN_SUCCESS = 'SAGA_LOGIN_SUCCESS';



//notification
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const ACCOUNT_SET = 'ACCOUNT_SET';
export const ACCOUNT_SELECTED = 'ACCOUNT_SELECTED';

export const APP_STATES = {
    AUTHENTICATED: 'AUTHENTICATED',
    NOT_AUTHENTICATED: 'NOT_AUTHENTICATED'
};

export const GET_APP_STATE = 'GET_APP_STATE';
export const SIGN_OUT = 'SIGN_OUT';